<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIHi6x9i\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIHi6x9i/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIHi6x9i.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIHi6x9i\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIHi6x9i\App_KernelDevDebugContainer([
    'container.build_hash' => 'IHi6x9i',
    'container.build_id' => '688d0c29',
    'container.build_time' => 1583959606,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIHi6x9i');
