<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\NoteController::index'], [], [['text', '/']], [], []],
    'matieres' => [[], ['_controller' => 'App\\Controller\\NoteController::matieres'], [], [['text', '/matieres']], [], []],
    'singleMatiere' => [['id'], ['_controller' => 'App\\Controller\\NoteController::singleMatiere'], [], [['text', '}'], ['variable', '', '[^/]+', 'id', true], ['text', '/singleMatiere/{']], [], []],
    'remove' => [['id'], ['_controller' => 'App\\Controller\\NoteController::removeMatiere'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/note/remove']], [], []],
];
